// Generated by `npm run db:types` from the live schema. Do not edit by hand.
/* eslint-disable @typescript-eslint/no-explicit-any */

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      brands: {
        Row: {
          id: string
          slug: string
          name: string
          sort: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          slug: string
          name: string
          sort?: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          slug?: string
          name?: string
          sort?: number
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      categories: {
        Row: {
          id: string
          slug: string
          name_he: string
          parent_id: string | null
          sort: number
          intro_he: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          slug: string
          name_he: string
          parent_id?: string | null
          sort?: number
          intro_he?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          slug?: string
          name_he?: string
          parent_id?: string | null
          sort?: number
          intro_he?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "categories_parent_id_fkey"
            columns: ["parent_id"]
            isOneToOne: false
            referencedRelation: "categories"
            referencedColumns: ["id"]
          }
        ]
      }
      deliveries: {
        Row: {
          id: string
          order_id: string
          proposed_windows: Json
          pickup_date: string | null
          pickup_shift: Database["public"]["Enums"]["delivery_shift"] | null
          dropoff_date: string | null
          dropoff_shift: Database["public"]["Enums"]["delivery_shift"] | null
          crew_name: string | null
          crew_phone: string | null
          status: string
          inspection_ok: boolean | null
          inspection_note: string | null
          admin_notes: string | null
          actual_cost_agorot: number | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          order_id: string
          proposed_windows?: Json
          pickup_date?: string | null
          pickup_shift?: Database["public"]["Enums"]["delivery_shift"] | null
          dropoff_date?: string | null
          dropoff_shift?: Database["public"]["Enums"]["delivery_shift"] | null
          crew_name?: string | null
          crew_phone?: string | null
          status?: string
          inspection_ok?: boolean | null
          inspection_note?: string | null
          admin_notes?: string | null
          actual_cost_agorot?: number | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          order_id?: string
          proposed_windows?: Json
          pickup_date?: string | null
          pickup_shift?: Database["public"]["Enums"]["delivery_shift"] | null
          dropoff_date?: string | null
          dropoff_shift?: Database["public"]["Enums"]["delivery_shift"] | null
          crew_name?: string | null
          crew_phone?: string | null
          status?: string
          inspection_ok?: boolean | null
          inspection_note?: string | null
          admin_notes?: string | null
          actual_cost_agorot?: number | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "deliveries_order_id_fkey"
            columns: ["order_id"]
            isOneToOne: true
            referencedRelation: "orders"
            referencedColumns: ["id"]
          }
        ]
      }
      delivery_zones: {
        Row: {
          city: string
          zone: string
          fee_agorot: number
          created_at: string
          updated_at: string
        }
        Insert: {
          city: string
          zone: string
          fee_agorot: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          city?: string
          zone?: string
          fee_agorot?: number
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      disputes: {
        Row: {
          id: string
          order_id: string
          opened_by: string
          reason: string
          description: string
          photo_paths: string[]
          status: string
          resolution_note: string | null
          refund_agorot: number
          resolved_at: string | null
          resolved_by: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          order_id: string
          opened_by: string
          reason: string
          description: string
          photo_paths?: string[]
          status?: string
          resolution_note?: string | null
          refund_agorot?: number
          resolved_at?: string | null
          resolved_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          order_id?: string
          opened_by?: string
          reason?: string
          description?: string
          photo_paths?: string[]
          status?: string
          resolution_note?: string | null
          refund_agorot?: number
          resolved_at?: string | null
          resolved_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "disputes_opened_by_fkey"
            columns: ["opened_by"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "disputes_opener_profile_fk"
            columns: ["opened_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "disputes_order_id_fkey"
            columns: ["order_id"]
            isOneToOne: false
            referencedRelation: "orders"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "disputes_resolved_by_fkey"
            columns: ["resolved_by"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          }
        ]
      }
      favorites: {
        Row: {
          user_id: string
          listing_id: string
          created_at: string
        }
        Insert: {
          user_id: string
          listing_id: string
          created_at?: string
        }
        Update: {
          user_id?: string
          listing_id?: string
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "favorites_listing_id_fkey"
            columns: ["listing_id"]
            isOneToOne: false
            referencedRelation: "listings"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "favorites_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          }
        ]
      }
      legacy_orders: {
        Row: {
          legacy_id: string
          legacy_status: string | null
          buyer_email: string | null
          seller_email: string | null
          item_legacy_id: string | null
          total_agorot: number | null
          created_at: string | null
          raw: Json
          imported_at: string
        }
        Insert: {
          legacy_id: string
          legacy_status?: string | null
          buyer_email?: string | null
          seller_email?: string | null
          item_legacy_id?: string | null
          total_agorot?: number | null
          created_at?: string | null
          raw: Json
          imported_at?: string
        }
        Update: {
          legacy_id?: string
          legacy_status?: string | null
          buyer_email?: string | null
          seller_email?: string | null
          item_legacy_id?: string | null
          total_agorot?: number | null
          created_at?: string | null
          raw?: Json
          imported_at?: string
        }
        Relationships: []
      }
      legacy_redirects: {
        Row: {
          legacy_id: string
          legacy_path: string | null
          new_path: string
          created_at: string
        }
        Insert: {
          legacy_id: string
          legacy_path?: string | null
          new_path: string
          created_at?: string
        }
        Update: {
          legacy_id?: string
          legacy_path?: string | null
          new_path?: string
          created_at?: string
        }
        Relationships: []
      }
      legacy_users: {
        Row: {
          legacy_id: string
          email: string
          full_name: string | null
          phone: string | null
          city: string | null
          raw: Json
          created_at: string
        }
        Insert: {
          legacy_id: string
          email: string
          full_name?: string | null
          phone?: string | null
          city?: string | null
          raw: Json
          created_at?: string
        }
        Update: {
          legacy_id?: string
          email?: string
          full_name?: string | null
          phone?: string | null
          city?: string | null
          raw?: Json
          created_at?: string
        }
        Relationships: []
      }
      listing_photos: {
        Row: {
          id: string
          listing_id: string
          storage_path: string
          sort: number
          alt_text: string | null
          width: number | null
          height: number | null
          created_at: string
        }
        Insert: {
          id?: string
          listing_id: string
          storage_path: string
          sort?: number
          alt_text?: string | null
          width?: number | null
          height?: number | null
          created_at?: string
        }
        Update: {
          id?: string
          listing_id?: string
          storage_path?: string
          sort?: number
          alt_text?: string | null
          width?: number | null
          height?: number | null
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "listing_photos_listing_id_fkey"
            columns: ["listing_id"]
            isOneToOne: false
            referencedRelation: "listings"
            referencedColumns: ["id"]
          }
        ]
      }
      listing_status_transitions: {
        Row: {
          from_status: Database["public"]["Enums"]["listing_status"]
          to_status: Database["public"]["Enums"]["listing_status"]
        }
        Insert: {
          from_status: Database["public"]["Enums"]["listing_status"]
          to_status: Database["public"]["Enums"]["listing_status"]
        }
        Update: {
          from_status?: Database["public"]["Enums"]["listing_status"]
          to_status?: Database["public"]["Enums"]["listing_status"]
        }
        Relationships: []
      }
      listings: {
        Row: {
          id: string
          slug: string
          seller_id: string
          title: string
          description: string
          category_id: string
          brand_id: string | null
          brand_free_text: string | null
          condition: Database["public"]["Enums"]["listing_condition"]
          width_cm: number
          depth_cm: number
          height_cm: number
          original_price_agorot: number | null
          price_agorot: number
          commission_pct_override: number | null
          resale_source_order_id: string | null
          status: Database["public"]["Enums"]["listing_status"]
          rejection_reason: string | null
          pickup_city: string
          pickup_street: string | null
          pickup_floor: number
          pickup_has_elevator: boolean
          needs_disassembly: boolean
          allow_self_pickup: boolean
          notes: string | null
          view_count: number
          published_at: string | null
          expires_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          slug: string
          seller_id: string
          title: string
          description?: string
          category_id: string
          brand_id?: string | null
          brand_free_text?: string | null
          condition: Database["public"]["Enums"]["listing_condition"]
          width_cm: number
          depth_cm: number
          height_cm: number
          original_price_agorot?: number | null
          price_agorot: number
          commission_pct_override?: number | null
          resale_source_order_id?: string | null
          status?: Database["public"]["Enums"]["listing_status"]
          rejection_reason?: string | null
          pickup_city: string
          pickup_street?: string | null
          pickup_floor?: number
          pickup_has_elevator?: boolean
          needs_disassembly?: boolean
          allow_self_pickup?: boolean
          notes?: string | null
          view_count?: number
          published_at?: string | null
          expires_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          slug?: string
          seller_id?: string
          title?: string
          description?: string
          category_id?: string
          brand_id?: string | null
          brand_free_text?: string | null
          condition?: Database["public"]["Enums"]["listing_condition"]
          width_cm?: number
          depth_cm?: number
          height_cm?: number
          original_price_agorot?: number | null
          price_agorot?: number
          commission_pct_override?: number | null
          resale_source_order_id?: string | null
          status?: Database["public"]["Enums"]["listing_status"]
          rejection_reason?: string | null
          pickup_city?: string
          pickup_street?: string | null
          pickup_floor?: number
          pickup_has_elevator?: boolean
          needs_disassembly?: boolean
          allow_self_pickup?: boolean
          notes?: string | null
          view_count?: number
          published_at?: string | null
          expires_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "listings_brand_id_fkey"
            columns: ["brand_id"]
            isOneToOne: false
            referencedRelation: "brands"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "listings_category_id_fkey"
            columns: ["category_id"]
            isOneToOne: false
            referencedRelation: "categories"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "listings_resale_source_fk"
            columns: ["resale_source_order_id"]
            isOneToOne: false
            referencedRelation: "orders"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "listings_seller_id_fkey"
            columns: ["seller_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "listings_seller_profile_fk"
            columns: ["seller_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          }
        ]
      }
      offers: {
        Row: {
          id: string
          listing_id: string
          buyer_id: string
          amount_agorot: number
          status: Database["public"]["Enums"]["offer_status"]
          counter_amount_agorot: number | null
          expires_at: string
          checkout_expires_at: string | null
          responded_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          listing_id: string
          buyer_id: string
          amount_agorot: number
          status?: Database["public"]["Enums"]["offer_status"]
          counter_amount_agorot?: number | null
          expires_at: string
          checkout_expires_at?: string | null
          responded_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          listing_id?: string
          buyer_id?: string
          amount_agorot?: number
          status?: Database["public"]["Enums"]["offer_status"]
          counter_amount_agorot?: number | null
          expires_at?: string
          checkout_expires_at?: string | null
          responded_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "offers_buyer_id_fkey"
            columns: ["buyer_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "offers_buyer_profile_fk"
            columns: ["buyer_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "offers_listing_id_fkey"
            columns: ["listing_id"]
            isOneToOne: false
            referencedRelation: "listings"
            referencedColumns: ["id"]
          }
        ]
      }
      order_events: {
        Row: {
          id: string
          order_id: string
          actor_id: string | null
          type: string
          payload: Json
          created_at: string
        }
        Insert: {
          id?: string
          order_id: string
          actor_id?: string | null
          type: string
          payload?: Json
          created_at?: string
        }
        Update: {
          id?: string
          order_id?: string
          actor_id?: string | null
          type?: string
          payload?: Json
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "order_events_actor_id_fkey"
            columns: ["actor_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "order_events_order_id_fkey"
            columns: ["order_id"]
            isOneToOne: false
            referencedRelation: "orders"
            referencedColumns: ["id"]
          }
        ]
      }
      order_status_transitions: {
        Row: {
          from_status: Database["public"]["Enums"]["order_status"]
          to_status: Database["public"]["Enums"]["order_status"]
        }
        Insert: {
          from_status: Database["public"]["Enums"]["order_status"]
          to_status: Database["public"]["Enums"]["order_status"]
        }
        Update: {
          from_status?: Database["public"]["Enums"]["order_status"]
          to_status?: Database["public"]["Enums"]["order_status"]
        }
        Relationships: []
      }
      orders: {
        Row: {
          id: string
          listing_id: string
          buyer_id: string
          seller_id: string
          offer_id: string | null
          status: Database["public"]["Enums"]["order_status"]
          item_agorot: number
          delivery_agorot: number
          surcharges: Json
          surcharges_agorot: number
          total_agorot: number
          commission_agorot: number
          seller_payout_agorot: number
          cancellation_fee_agorot: number
          refund_agorot: number
          delivery_method: string
          dropoff_city: string | null
          dropoff_street: string | null
          dropoff_floor: number | null
          dropoff_has_elevator: boolean | null
          dropoff_notes: string | null
          payment_provider: string
          payment_ref: string | null
          cancellation_reason: string | null
          protection_expires_at: string | null
          confirmed_at: string | null
          scheduled_at: string | null
          picked_up_at: string | null
          delivered_at: string | null
          completed_at: string | null
          cancelled_at: string | null
          disputed_at: string | null
          refunded_at: string | null
          paid_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          listing_id: string
          buyer_id: string
          seller_id: string
          offer_id?: string | null
          status?: Database["public"]["Enums"]["order_status"]
          item_agorot: number
          delivery_agorot?: number
          surcharges?: Json
          surcharges_agorot?: number
          total_agorot: number
          commission_agorot: number
          seller_payout_agorot: number
          cancellation_fee_agorot?: number
          refund_agorot?: number
          delivery_method: string
          dropoff_city?: string | null
          dropoff_street?: string | null
          dropoff_floor?: number | null
          dropoff_has_elevator?: boolean | null
          dropoff_notes?: string | null
          payment_provider?: string
          payment_ref?: string | null
          cancellation_reason?: string | null
          protection_expires_at?: string | null
          confirmed_at?: string | null
          scheduled_at?: string | null
          picked_up_at?: string | null
          delivered_at?: string | null
          completed_at?: string | null
          cancelled_at?: string | null
          disputed_at?: string | null
          refunded_at?: string | null
          paid_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          listing_id?: string
          buyer_id?: string
          seller_id?: string
          offer_id?: string | null
          status?: Database["public"]["Enums"]["order_status"]
          item_agorot?: number
          delivery_agorot?: number
          surcharges?: Json
          surcharges_agorot?: number
          total_agorot?: number
          commission_agorot?: number
          seller_payout_agorot?: number
          cancellation_fee_agorot?: number
          refund_agorot?: number
          delivery_method?: string
          dropoff_city?: string | null
          dropoff_street?: string | null
          dropoff_floor?: number | null
          dropoff_has_elevator?: boolean | null
          dropoff_notes?: string | null
          payment_provider?: string
          payment_ref?: string | null
          cancellation_reason?: string | null
          protection_expires_at?: string | null
          confirmed_at?: string | null
          scheduled_at?: string | null
          picked_up_at?: string | null
          delivered_at?: string | null
          completed_at?: string | null
          cancelled_at?: string | null
          disputed_at?: string | null
          refunded_at?: string | null
          paid_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "orders_buyer_id_fkey"
            columns: ["buyer_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "orders_buyer_profile_fk"
            columns: ["buyer_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "orders_listing_id_fkey"
            columns: ["listing_id"]
            isOneToOne: false
            referencedRelation: "listings"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "orders_offer_id_fkey"
            columns: ["offer_id"]
            isOneToOne: false
            referencedRelation: "offers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "orders_seller_id_fkey"
            columns: ["seller_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "orders_seller_profile_fk"
            columns: ["seller_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          }
        ]
      }
      outbound_events: {
        Row: {
          id: string
          type: string
          channel: string
          recipient: string
          recipient_role: string | null
          subject: string | null
          payload: Json
          idempotency_key: string | null
          status: string
          error: string | null
          sent_at: string | null
          created_at: string
        }
        Insert: {
          id?: string
          type: string
          channel?: string
          recipient: string
          recipient_role?: string | null
          subject?: string | null
          payload?: Json
          idempotency_key?: string | null
          status?: string
          error?: string | null
          sent_at?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          type?: string
          channel?: string
          recipient?: string
          recipient_role?: string | null
          subject?: string | null
          payload?: Json
          idempotency_key?: string | null
          status?: string
          error?: string | null
          sent_at?: string | null
          created_at?: string
        }
        Relationships: []
      }
      payouts: {
        Row: {
          id: string
          order_id: string
          seller_id: string
          amount_agorot: number
          status: string
          paid_at: string | null
          method_note: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          order_id: string
          seller_id: string
          amount_agorot: number
          status?: string
          paid_at?: string | null
          method_note?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          order_id?: string
          seller_id?: string
          amount_agorot?: number
          status?: string
          paid_at?: string | null
          method_note?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "payouts_order_id_fkey"
            columns: ["order_id"]
            isOneToOne: true
            referencedRelation: "orders"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "payouts_seller_id_fkey"
            columns: ["seller_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "payouts_seller_profile_fk"
            columns: ["seller_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          }
        ]
      }
      profiles: {
        Row: {
          id: string
          email: string
          full_name: string | null
          phone: string | null
          city: string | null
          role: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          email: string
          full_name?: string | null
          phone?: string | null
          city?: string | null
          role?: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          email?: string
          full_name?: string | null
          phone?: string | null
          city?: string | null
          role?: string
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "profiles_id_fkey"
            columns: ["id"]
            isOneToOne: true
            referencedRelation: "users"
            referencedColumns: ["id"]
          }
        ]
      }
      rate_limits: {
        Row: {
          bucket: string
          subject: string
          window_start: string
          count: number
        }
        Insert: {
          bucket: string
          subject: string
          window_start: string
          count?: number
        }
        Update: {
          bucket?: string
          subject?: string
          window_start?: string
          count?: number
        }
        Relationships: []
      }
      saved_searches: {
        Row: {
          id: string
          user_id: string
          label: string | null
          query: Json
          channel: string
          active: boolean
          last_run_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          label?: string | null
          query: Json
          channel?: string
          active?: boolean
          last_run_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          label?: string | null
          query?: Json
          channel?: string
          active?: boolean
          last_run_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "saved_searches_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          }
        ]
      }
      site_config: {
        Row: {
          key: string
          value: Json
          description: string | null
          updated_at: string
          is_public: boolean
        }
        Insert: {
          key: string
          value: Json
          description?: string | null
          updated_at?: string
          is_public?: boolean
        }
        Update: {
          key?: string
          value?: Json
          description?: string | null
          updated_at?: string
          is_public?: boolean
        }
        Relationships: []
      }
    }
    Views: {
      kpi_catalog: {
        Row: {
          active_listings: number | null
          pending_review: number | null
          sold_listings: number | null
          expired_listings: number | null
        }
        Relationships: []
      }
      kpi_delivery_by_zone: {
        Row: {
          zone: string | null
          category: string | null
          deliveries: number | null
          charged_agorot: number | null
          actual_cost_agorot: number | null
          margin_agorot: number | null
        }
        Relationships: []
      }
      kpi_overview: {
        Row: {
          completed_orders: number | null
          gmv_agorot: number | null
          take_agorot: number | null
          delivery_revenue_agorot: number | null
          live_orders: number | null
          cancelled_orders: number | null
        }
        Relationships: []
      }
      kpi_seller_response: {
        Row: {
          total_requests: number | null
          confirmed: number | null
          timed_out: number | null
          confirm_rate_pct: number | null
          avg_hours_to_confirm: number | null
        }
        Relationships: []
      }
    }
    Functions: {
      consume_rate_limit: {
        Args: {
          p_bucket?: string | null
          p_subject?: string | null
          p_limit?: number | null
          p_window_seconds?: number | null
          allowed?: string | null
          remaining?: string | null
          resets_at?: string | null
        }
        Returns: unknown
      }
      create_order: {
        Args: {
          p_listing_id?: string | null
          p_buyer_id?: string | null
          p_item_agorot?: number | null
          p_delivery_agorot?: number | null
          p_surcharges?: Json | null
          p_surcharges_agorot?: number | null
          p_total_agorot?: number | null
          p_commission_agorot?: number | null
          p_seller_payout_agorot?: number | null
          p_delivery_method?: string | null
          p_payment_provider?: string | null
          p_offer_id?: string | null
          p_dropoff_city?: string | null
          p_dropoff_street?: string | null
          p_dropoff_floor?: number | null
          p_dropoff_has_elevator?: boolean | null
          p_dropoff_notes?: string | null
        }
        Returns: Database["public"]["Tables"]["orders"]["Row"]
      }
      mark_listing_sold_for_order: {
        Args: {
          p_order_id?: string | null
          p_actor?: string | null
        }
        Returns: undefined
      }
      prune_rate_limits: {
        Args: {
          p_older_than?: unknown | null
        }
        Returns: number
      }
      record_order_event: {
        Args: {
          p_order_id?: string | null
          p_actor?: string | null
          p_type?: string | null
          p_payload?: Json | null
        }
        Returns: undefined
      }
      release_listing_for_order: {
        Args: {
          p_order_id?: string | null
          p_actor?: string | null
        }
        Returns: undefined
      }
      transition_listing: {
        Args: {
          p_listing_id?: string | null
          p_to?: Database["public"]["Enums"]["listing_status"] | null
          p_actor?: string | null
          p_reason?: string | null
        }
        Returns: Database["public"]["Tables"]["listings"]["Row"]
      }
      transition_order: {
        Args: {
          p_order_id?: string | null
          p_to?: Database["public"]["Enums"]["order_status"] | null
          p_actor?: string | null
          p_event_type?: string | null
          p_payload?: Json | null
        }
        Returns: Database["public"]["Tables"]["orders"]["Row"]
      }
    }
    Enums: {
      delivery_shift: "morning" | "afternoon" | "evening"
      listing_condition: "like_new" | "excellent" | "good" | "fair"
      listing_status: "draft" | "pending_review" | "active" | "reserved" | "sold" | "rejected" | "expired" | "removed"
      offer_status: "pending" | "accepted" | "declined" | "countered" | "expired"
      order_status: "pending_seller_confirmation" | "confirmed" | "delivery_scheduled" | "picked_up" | "delivered" | "completed" | "cancelled" | "disputed" | "refunded"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
};

type PublicSchema = Database['public'];

export type Tables<T extends keyof (PublicSchema['Tables'] & PublicSchema['Views'])> =
  (PublicSchema['Tables'] & PublicSchema['Views'])[T] extends { Row: infer R } ? R : never;

export type TablesInsert<T extends keyof PublicSchema['Tables']> =
  PublicSchema['Tables'][T] extends { Insert: infer I } ? I : never;

export type TablesUpdate<T extends keyof PublicSchema['Tables']> =
  PublicSchema['Tables'][T] extends { Update: infer U } ? U : never;

export type Enums<T extends keyof PublicSchema['Enums']> = PublicSchema['Enums'][T];
